version: '3.3'
services:

    # Runs the bitcoind service, and exposes itself to the lnd_service. 
    bitcoind_service:
        image: bitcoind_image
        build:
            context: bitcoind/
        env_file:
            - bitcoind/bitcoind.env
        container_name: bitcoind_container
        volumes:
            - ~/.bitcoin:/root/.bitcoin
        restart: always
        entrypoint: ["./start-bitcoind.sh"]


    # Runs the lnd service.
    lnd_service:
        image: lnd_image
        env_file:
            - lnd/lnd.env
        build:
            context: lnd/
        ports:
            - "10009:10009"
            - "8080:8080"
            - "9735:9735"
        expose:
            - "9735"
            - "8080"
            - "10009"
        container_name: lnd_container
        volumes:
          - ~/.lnd:/root/.lnd
        depends_on:
            - bitcoind_service
        restart: always
        entrypoint: ["./start-lnd.sh"]

